<!--
The type of the attribute "id" of Biomaterials needs
to be CDATA instead of ID, since DTD doesn't allow
IDs that start with a number

It's a template in DTD language d
-->
<!DOCTYPE BiomaterialList [
	<!ELEMENT BiomaterialList (Products)>
	<!ELEMENT Products (Biomaterial+)>
    <!ELEMENT Biomaterial (product_name, price_unit, available_units)>
    <!ATTLIST Biomaterial biomaterialId CDATA #REQUIRED>
    <!ELEMENT product_name (#PCDATA)>
    <!ELEMENT price_unit (#PCDATA)>
    <!ELEMENT available_units (#PCDATA)>
]>
<BiomaterialList>
    <Products>
        <Biomaterial biomaterialId="1">
            <product_name>Metal bar</product_name>
            <price_unit>34.0</price_unit>
            <available_units>30</available_units>
        </Biomaterial>
    </Products>
</BiomaterialList>
